plugins:

  exec:
    executor: central_deployment_agent
    package_name: cloudify-execution-plugin
    package_version: '0.4.0'

data_types:

  cloudify.types.exec.Package:
    properties:
      resource_dir:
        description: >
          A directory under the blueprint root,
          which content needs to be copied and kept unchanged.
        default: ''
      resource_list:
        description: >
          A list of file paths under the blueprint root,
          which need to be filled with values of template_variables.
        default: []
      template_variables:
        description: A dict containing variables as key-values.
        default: {}

node_types:

  cloudify.nodes.Execution:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      resource_config:
        type: cloudify.types.exec.Package
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        create: &exec_op
          implementation: exec.exec_plugin.tasks.execute
          inputs:
            resource_config:
              type: cloudify.types.exec.Package
              default: { get_property: [ SELF, resource_config ] }
            file_to_source:
              type: string
              default: exec
