plugins:

  exec:
    executor: central_deployment_agent
    source: cloudify-execution-plugin
    package_name: cloudify-execution-plugin
    package_version: '0.4.0'

data_types:

  cloudify.types.exec.Package:
    properties:
      resource_dir:
        description: >
          A directory under the blueprint root,
          which content needs to be copied and kept unchanged.
        default: ''
      resource_list:
        description: >
          A list of file paths under the blueprint root,
          which need to be filled with values of template_variables.
        default: []
      template_variables:
        description: A dict containing variables as key-values.
        default: {}


relationships:

  cloudify.relationships.execute_from_package:
    derived_from: cloudify.relationships.depends_on
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: exec.exec_plugin.tasks.attach_execution_node
        unlink:
          implementation: exec.exec_plugin.tasks.detach_execution_node

  cloudify.relationships.package_connected_to_data:
    derived_from: cloudify.relationships.connected_to

  cloudify.relationships.execution_connected_to_key:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: exec.exec_plugin.tasks.attach_key
        unlink:
          implementation: exec.exec_plugin.tasks.detach_key


node_types:

  cloudify.nodes.exec.Package:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      resource_config:
        type: cloudify.types.exec.Package
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: exec.exec_plugin.tasks.init_package
        configure:
          implementation: exec.exec_plugin.tasks.get_paths
          inputs:
            resource_config:
              default: { get_property: [ SELF, resource_config ] }

  cloudify.nodes.exec.Key:
    derived_from: cloudify.nodes.Root
    properties:
      keypath:
        description: >
          Path to the SSH key in Cloudify Manager filesystem
        type: string
      dirname:
        description: >
          Name of the directory inside blueprint, where SSH key should be saved
        type: string
        default: keys
    interfaces:
      cloudify.interfaces.lifecycle:
        start:
          implementation: exec.exec_plugin.tasks.retrieve_key
        stop:
          implementation: exec.exec_plugin.tasks.remove_key

  cloudify.nodes.Execution:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      resource_config:
        type: cloudify.types.exec.Package
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        create: {}
        start: &exec_op
          implementation: exec.exec_plugin.tasks.execute
          inputs:
            resource_config:
              default: { get_property: [ SELF, resource_config ] }
            file_to_source:
              type: string
              default: exec
