plugins:

  exec:
    # executor: host_agent
    executor: central_deployment_agent
    # source: https://github.com/cloudify-incubator/cloudify-execution-plugin/archive/0.4.0.zip
    source: cloudify-execution-plugin
    package_name: cloudify-execution-plugin
    package_version: '0.4.0'

data_types:

  cloudify.types.exec.Package:
    properties:
      resource_dir:
        description: >
          A directory under the blueprint root,
          which content needs to be copied and kept unchanged.
        default: ''
      resource_list:
        description: >
          A list of file paths under the blueprint root,
          which need to be filled with values of template_variables.
        default: []
      template_variables:
        description: A dict containing variables as key-values.
        default: {}
      # merged_list:
      #   description: >
      #     A list of all file paths under the resource_dir.
      #   default: []


relationships:

  cloudify.relationships.execute_from_package:
    derived_from: cloudify.relationships.depends_on
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: exec.exec_plugin.tasks.attach_execution_node
        unlink:
          implementation: exec.exec_plugin.tasks.detach_execution_node

  cloudify.relationships.package_connected_to_data:
    derived_from: cloudify.relationships.connected_to
    target_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: exec.exec_plugin.tasks.retrieve_data
          inputs:
            resource_config:
              default: { get_property: [SOURCE, resource_config] }
            keypath:
              default: ''
        postconfigure:
          implementation: exec.exec_plugin.tasks.get_paths
          inputs:
            resource_config:
              default: { get_property: [SOURCE, resource_config] }
        unlink:
          implementation: exec.exec_plugin.tasks.clear_data
          inputs:
            resource_config:
              default: { get_property: [SOURCE, resource_config] }
            keypath:
              default: ''


node_types:

  cloudify.nodes.exec.Package:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      resource_config:
        type: cloudify.types.exec.Package
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: exec.exec_plugin.tasks.init_package
        # configure:
        #   implementation: exec.exec_plugin.tasks.retrieve_private_key
        #   inputs:
        #     resource_config:
        #       default: { get_property: [ SELF, resource_config ] }
        #     keypath:
        #       default: ''
        # start:
        # configure:
        #   implementation: exec.exec_plugin.tasks.get_paths
        #   inputs:
        #     resource_config:
        #       default: { get_property: [ SELF, resource_config ] }
        # stop:
        #   implementation: exec.exec_plugin.tasks.remove_private_key
        #   inputs:
        #     resource_config:
        #       default: { get_property: [ SELF, resource_config ] }
        #     keypath:
        #       default: ''

  cloudify.nodes.Execution:
    derived_from: cloudify.nodes.SoftwareComponent
    properties:
      resource_config:
        type: cloudify.types.exec.Package
        required: false
    interfaces:
      cloudify.interfaces.lifecycle:
        create: {}
        start: &exec_op
          implementation: exec.exec_plugin.tasks.execute
          inputs:
            resource_config:
              default: { get_property: [ SELF, resource_config ] }
            file_to_source:
              type: string
              default: exec
